version: "1.0"
server:
  port: 8888
redisQueues:
  redisHost: 'localhost'
  redisPort: 6379
  address: 'redis-queues'
  httpRequestHandlerEnabled: true
  processorAddress: 'redis-queues-processor'
segmentation:
  instances: 200
attributesCalculation:
  instances: 10
memberFunctions:
  instances: 20
membersSummary:
  instances: 20
