version: "1.0"
server:
  port: 8888
db:
  host: 'localhost'
  port: 8027
  database: 'senders_poc'
  user: 'msandbox'
  password: 'msandbox'
redisQueues:
  redisHost: 'localhost'
  redisPort: 6379
  address: 'redis-queues'
  httpRequestHandlerEnabled: true
  processorAddress: 'redis-queues-processor'
segmentation:
  instances: 200
attributesCalculation:
  instances: 10
memberFunctions:
  instances: 20
membersSummary:
  instances: 20
